### ISSUE TITLE
fix the fact that clients don't receive the correct states for gestures when loading other player's models

### ISSUE THREAD

**Issue by chyzman** [tom5454/CustomPlayerModels#294] opened 2022-09-29 15:25 UTC
when a client first renders another player's model the gestures/toggles/values/whatever dont get synced correctly until the player updates a gestures or reloads there model

**Comment by tom5454** [comment] 2022-10-01 17:21
Are you on fabric?

**Comment by chyzman** [comment] 2022-10-01 17:29
it happens on both tho possibly more so on fabric

**Comment by tom5454** [comment] 2022-10-02 12:46
Can't reproduce on Forge, can on Fabric, Duplicate of #282

**Closed by tom5454** 2022-10-02 12:46 UTC
