### ISSUE TITLE
"Rendering custom Held Item position" Crash

### ISSUE THREAD

**Issue by PeskyPlayz953** [tom5454/CustomPlayerModels#434] opened 2023-06-11 21:32 UTC
[crash-2023-06-11_15.47.46-client.txt](https://github.com/tom5454/CustomPlayerModels/files/11715759/crash-2023-06-11_15.47.46-client.txt)
[message.txt](https://github.com/tom5454/CustomPlayerModels/files/11715760/message.txt)
For some context, I'm helping develop/test a modpack, its on Forge, when teleporting to another player from far away, the game crashes, this issue is decently common. The other player, referred to as Magnus, has CPM installed, the server has it, and so do I, but he does not use custom models, I use a not so complex model, with 10-15 cubes and some custom animations. This is causing major problems for us and we want to continue using the mod, but the issues, although uncommon, have caused the mod to become unusable. We are unsure if its something as small as the create train tracks next to the location, or something unfixable.

**Comment by tom5454** [comment] 2023-06-11 22:57
Duplicate of #372, #433 
Will be fixed in the next version.

**Closed by tom5454** 2023-06-11 22:57 UTC
