### ISSUE TITLE
how do i use the menu?

### ISSUE THREAD

**Issue by cs234477** [tom5454/CustomPlayerModels#145] opened 2021-09-15 01:31 UTC
ok, the same question as before but rephrased, the image below shows the menu
![Screenshot (6)](https://user-images.githubusercontent.com/90009319/133355580-5f7d6e49-9ce7-4696-82f5-e0e453494876.png)

I want to know how to use it and put my models in there, can someone tell me how I put 1 of the models in the skins folder for Minecraft and nothing happened, can someone explain to me how it works?
thx

**Comment by Xigzagamer** [comment] 2021-09-15 04:40
You're using it wrong, that's for the model files exported by the mod. Not the skin files, there's a difference. When you're exporting switch it to model mode and it will automatically put your exported model in the right place when you save it. Look for a mode selector when you hit the export button.

**Comment by tom5454** [comment] 2021-10-02 15:36
Duplicate of #136

**Closed by tom5454** 2021-10-02 15:36 UTC
