### ISSUE TITLE
Can't Export From Blockbench

### ISSUE THREAD

**Issue by Grumflumbus** [tom5454/CustomPlayerModels#347] opened 2023-01-10 16:10 UTC
![image_2023-01-10_111025707](https://user-images.githubusercontent.com/122385130/211602927-027b6200-ae78-481c-8662-dbefd748df76.png)

**Comment by tom5454** [comment] 2023-01-11 11:53
Duplicate of #346

**Closed by tom5454** 2023-01-11 11:53 UTC
