### ISSUE TITLE
[Enhancement]Some form of "Advanced" control for animations

### ISSUE THREAD

**Issue by RedRain0o0** [tom5454/CustomPlayerModels#411] opened 2023-05-01 20:31 UTC
I'm suggesting the ability to control the time between individual frames, as-well as the type of interpolation between 2 frames. (Please, it would be so useful for so many things)

**Comment by tom5454** [comment] 2024-01-14 19:02
Duplicate of #192

**Closed by tom5454** 2024-01-14 19:02 UTC
