### ISSUE TITLE
Blockbench plugin error

### ISSUE THREAD

**Issue by DearFox** [tom5454/CustomPlayerModels#343] opened 2023-01-07 07:14 UTC
I get an error when saving.
I converted my model from skin format to bedrock legacy format and then to cpm format through the built-in blockbench function and after that when I try to save - the plugin gives an error

![image](https://user-images.githubusercontent.com/59219907/211138747-97f535ef-2aef-42d1-b041-29e16d4d4584.png)
TypeError: fs.existsSync is not a function
    at uIb (<anonymous>:1655:31)
    at Function.JIb (<anonymous>:1664:55)
    at Codec.d (<anonymous>:18:47)
    at Function.LJb (<anonymous>:1699:62)
    at Object.d [as custom_writer] (<anonymous>:18:47)
    at Object.writeFile (file_system.js:364:12)
    at Object.export (file_system.js:337:15)
    at DJb (<anonymous>:1693:258)
    at Function.bKb (<anonymous>:1708:60)
    at d (<anonymous>:18:47)

**Comment by tom5454** [comment] 2023-01-07 11:41
Duplicate of #341

**Closed by tom5454** 2023-01-07 11:41 UTC
