### ISSUE TITLE
Render scaling forces cube visibility ingame

### ISSUE THREAD

**Issue by The-Weeb-Guy** [tom5454/CustomPlayerModels#699] opened 2024-10-26 04:32 UTC
On non-experimental exports any animation that changes the render scale of a hidden by default cube will force the cube to be visible.
The attached zip file contains the project file in which i discovered this weird behavior, it is just a some cubes and a single toggle animation.
[komarusoundengine2.zip](https://github.com/user-attachments/files/17529006/komarusoundengine2.zip)
Bug was found on CPM 0.6.19a Forge version 47.3.7 1.20.1

**Comment by tom5454** [comment] 2024-12-03 18:34
Duplicate of #323

Any cube animation will force the visibility on the normal export option.
The normal export option must animate all of the cube properties every frame, it's a limitation of the old system. Due to a bug the visibility is always animated to 'show' unless you have visibility changes during the animation.

**Closed by tom5454** 2024-12-03 18:34 UTC
