### ISSUE TITLE
(Suggestion)  Ability to export as a .obj or other 3d program compatible file??

### ISSUE THREAD

**Issue by Woopagadon17** [tom5454/CustomPlayerModels#198] opened 2022-03-09 04:08 UTC
Would like to state that this mod is an absolute BANGER!

My request is that if I could see support for exporting a model as a .obj or .fbx file to use in Blender, C4D, Maya, etc.

Wanted to do a funny and put some of the playermodels I made into Risk of Rain 2 lmao.

Keep up the AMAZING work!!!

**Comment by tom5454** [comment] 2022-10-01 17:46
Duplicate of #198

**Closed by tom5454** 2022-10-01 17:46 UTC
