### ISSUE TITLE
(BUG) Animated hidden objects display unhidden in-game.

### ISSUE THREAD

**Issue by FelisMoon** [tom5454/CustomPlayerModels#462] opened 2023-07-27 21:53 UTC
If a block is -hidden by default- and is used trough the entirety of an animation without being unhidden, the block will unhide in-game during that animation, when the editor shows it should not.

Here are the steps to replicate it:

1. Start a new project and duplicate the head. Make one of the heads -glowing eyes- to differentiate them and apply -hidden by default-.

2. Create an animation where both heads move in the same pattern, while one remains hidden and the other remains shown, like this:
![image](https://github.com/tom5454/CustomPlayerModels/assets/81988520/eae57ecf-e7df-4e89-823d-559ee396aa70)

3. You'll see in the editor the animation correctly displays the unhidden main head only. (both in animation test and setup) but while testing in-game, the player model will unhide the glow head and overlap both of them, effectively rendering them differently to the editor and showing a hidden object that was never unhidden by the player, like this:
![2023-07-27_18 45 52](https://github.com/tom5454/CustomPlayerModels/assets/81988520/295058d5-3021-468a-9c7b-878e8c021e7f)

Why should this be fixed with importance? 

- It currently makes impossible one technique for toggle model swaps that share animations. Say you wanna replace an arm with a toggle animation, and decide to duplicate the arm with the copy animations feature. You hide one and unhide the other with the intention to swap them back with a toggle layer, leaving the hidden arm with a bunch of animations where it never gets manually unhidden by them. This will cause the alternate arm to pop in EVERY TIME an animation calls for it EVEN when the toggle is off, which is more or less what happened with my model. (Take a shot everytime i said hidden and unhidden)

- Because the editor displays the animation without errors, users may proceed to continue adding content that may have to be deleted in order to fix the issue, until they realize by testing in-game.

- This bug appears to happen on mod version 0.6.9a in ANY Minecraft version.

**Comment by tom5454** [comment] 2023-07-28 13:53
Duplicate of #323 
Make a 0x0x0 sized cube that controls the visible/hidden effect, then construct the second part under that.
This will be fixed when I clean up the project formats.

**Closed by tom5454** 2023-07-28 13:53 UTC

**Comment by FelisMoon** [comment] 2023-07-28 14:47
Thanks SO MUCH for the workaround! Ive been trying a lot of stuff and that didn't come up to me! Thanks for making such a beautiful mod and tool! <3
