### ISSUE TITLE
skin glitch when converting vanilla parts

### ISSUE THREAD

**Issue by cs234477** [tom5454/CustomPlayerModels#133] opened 2021-09-02 22:08 UTC
so, I just downloaded the mod, and I clicked convert vanilla parts but my skin keeps disappearing, basically, the model goes pitch black and I can't put the skin back on because it's still there, how do I fix this issue?

**Comment by tom5454** [comment] 2021-09-04 11:21
Duplicate of #122

**Closed by tom5454** 2021-09-04 11:21 UTC
