### ISSUE TITLE
Head yaw breaks with pehkui on 1.20.2 CPM version 6.13

### ISSUE THREAD

**Issue by GlitchTrap-1987** [tom5454/CustomPlayerModels#537] opened 2023-12-26 18:37 UTC
So when I look left it turns fully to the right for some reason I have immersive portals which likes to break it instantly no matter what when I enter a portal but even without it, it still breaks most likely with pehkui since it never did it till I installed pehkui. please fix this cause I hate this and I just want my models to look nice not break with weird yaw animations snapping to the right when I look anywhere near the left. If there is a fix for it in survival without killing myself every time then tell me. Shields fix it but it seems like because i dont have a climbing anim it breaks when i climb

**Comment by tom5454** [comment] 2023-12-27 17:51
Duplicate of #527

**Closed by tom5454** 2023-12-27 17:51 UTC
