### ISSUE TITLE
[Suggestion] Global orientation checkbox

### ISSUE THREAD

**Issue by BlackTalons** [tom5454/CustomPlayerModels#541] opened 2024-01-12 05:20 UTC
An option for a block to use global orientation instead if inheriting it from the parent block. Currently this can be done with a series of compensating bones, but with more complex models the part tree becomes unnecessarily extensive.

**Comment by tom5454** [comment] 2024-01-14 18:58
Duplicate of #38

**Closed by tom5454** 2024-01-14 18:58 UTC
