### ISSUE TITLE
Head Yaw animation gets locked to a side when performing certain actions

### ISSUE THREAD

**Issue by terminalvortex** [tom5454/CustomPlayerModels#523] opened 2023-10-31 08:47 UTC
Minecraft Version 1.20.1
Fabric 0.14.21
API vers 0.90.0
CPM 0.6.12a

When doing certain actions in-game (not in the "test" section of the editor) custom head yaw animations will "break", causing the model to be looking to one side (either right or left.) These actions include
-Flying with elytra
-Riding a horse
-Sleeping (Inconsistently)

The only way to fix this behavior is to ride in a boat. The model's head root has Vanilla Animations disabled [VH], and the yaw animation itself is 12 frames, set to additive, on Polynomial Single, and has priority over the problem gestures. Setting the priority to be lower than the affected gestures does not resolve the issue (with the exception of sleeping)

**Comment by tom5454** [comment] 2023-11-01 19:13
Duplicate of #502

**Closed by tom5454** 2023-11-01 19:13 UTC
