### ISSUE TITLE
(suggestion) crawl animation [hard but possible]

### ISSUE THREAD

**Issue by keenan1127** [tom5454/CustomPlayerModels#510] opened 2023-10-15 19:49 UTC
would likely need to have more complicated ways of working, but basically Minecraft can tell when they are swimming and when they are crawling, due to swimming having a leaning-esque feature while crawling stays flat, you could maybe use this same check and make an animation that overrides the swimming animation when it's needed.

same idea could apply to other shared animations like crouching & being in a crouching-height area while not holding shift.

**Comment by tom5454** [comment] 2024-01-14 18:53
Added crawling animation in the latest release, Duplicate of #355

**Closed by tom5454** 2024-01-14 18:53 UTC
