### ISSUE TITLE
Head Pitch/Yaw animations ignore the Hidden By Default feature

### ISSUE THREAD

**Issue by piper-pulsar** [tom5454/CustomPlayerModels#548] opened 2024-01-15 10:19 UTC
when I add a cube to the head pitch or yaw animations, and set it to Hidden By Default, it'll ignore the hidden by default feature and become visible anyway. I have a cube that follows the player's yaw position but is only supposed to be visible when on low HP, but its now constantly visible regardless of what HP the player is on. Taking it out of the yaw position animation fixes the issue. Not sure if this an intentional or if there's a workaround.

im using version 0.6.14 of the mod in fabric 1.20.1 !!

**Comment by tom5454** [comment] 2024-01-15 14:25
Duplicate of #323

**Closed by tom5454** 2024-01-15 14:25 UTC
