### ISSUE TITLE
Flashing glow

### ISSUE THREAD

**Issue by Arjection** [tom5454/CustomPlayerModels#248] opened 2022-07-17 12:05 UTC
Every time I try to make a character with any bit of animation the glow effect on my skin seems to flash non stop I have tried seeing if it was just the shader by messing with lighting settings and I even uninstalled the mod and reinstalled it.

**Comment by tom5454** [comment] 2022-08-15 17:10
Duplicate of #245

**Closed by tom5454** 2022-08-15 17:10 UTC
