### ISSUE TITLE
DarkRPG+Mod crashes on startup

### ISSUE THREAD

**Issue by GrandXXX** [tom5454/CustomPlayerModels#581] opened 2024-03-20 16:54 UTC
Hello! I have an interesting question... Is there any way I can make "Customizable player models (fabric)" work with the darkrpg modpack? There's an origin (sculker) which uses a different model, but it always crashes when I try to start it up, is there anything I can fix it? I've tried running it without DARKRPG (origins, sculker, pehkui, CPM) and it worked fine, but my guess is that one of the mods is crashing when paired with CPM, can anyone help me? (I've already tried messaging the sculker dewv and dark origin devs, this is my last hope)

additional info:

Sculker: https://www.curseforge.com/minecraft/mc-mods/sculker-origin-class

CPM: https://www.curseforge.com/minecraft/mc-mods/custom-player-models-fabric

Pehkui is used already in the modpack

I'm also attaching the crash report

[crash-2024-03-19_19.43.37-client.txt](https://github.com/tom5454/CustomPlayerModels/files/14670046/crash-2024-03-19_19.43.37-client.txt)

**Comment by tom5454** [comment] 2024-03-25 15:43
Remove `cosmetica`
Duplicate of #261

**Closed by tom5454** 2024-03-25 15:43 UTC
