### ISSUE TITLE
Colours not always working correctly for coloured armour.(and extra bug with blockbench)

### ISSUE THREAD

**Issue by URGaming123** [tom5454/CustomPlayerModels#383] opened 2023-03-06 16:22 UTC
I keep getting wrong colours on my model when I try dyed armour I don't exactly know why this is happening nor how to recreate it but it happens to the shoulders and the left foot. 

![image](https://user-images.githubusercontent.com/29049799/223168486-4647092f-9557-4fb6-a412-cef0e03ba57c.png)
(the white part is the shoulder and pink is the Chestplate I'm unsure whether I am doing something wrong but it keeps happening no matter what I try.)

And also when using a converted model from generic model to cpm the texture screws up in game and is black and probably has the max texture limit in the skin settings tab. (my model worked with the old cpm blockbench plugin normally.)

**Comment by tom5454** [comment] 2024-05-31 19:39
Duplicate of #604

**Closed by tom5454** 2024-05-31 19:39 UTC
