### ISSUE TITLE
Real Camera doesn't work nicely with a custom animation file installed 

### ISSUE THREAD

**Issue by Blergonos** [tom5454/CustomPlayerModels#442] opened 2023-06-15 11:19 UTC
The mod works fine when the CPM mod is off. But when I download a custom animation file, it makes weird camera glitches. There is a setting in the real camera mod that sort of fix the issues, but not completely, more like lessen the effects. The weird camera issues are mainly the camera clipping in to the the player model, there making me see my player model insides and also making it difficult to see forward or in some camera positions.

 https://www.youtube.com/watch?v=xvHTAhECw1I&t=408s&pp=ygUmYmV0dGVyIHBsYXllciBhbmltYXRpb25zIG1vZCBtaW5lY3JhZnQ%3D

I'm using this guys animation pack

**Comment by tom5454** [comment] 2023-06-16 12:48
Duplicate of #417

**Closed by tom5454** 2023-06-16 12:48 UTC

**Comment by Blergonos** [comment] 2023-06-18 10:23
> Duplicate of #417

oh sorry i didnt see the duplicate. ill will close
