### ISSUE TITLE
 They don't load cmproject files in blockbench

### ISSUE THREAD

**Issue by iFelipeGz** [tom5454/CustomPlayerModels#287] opened 2022-09-10 00:56 UTC
When opening a .cmproject file it does not load, this happens to me with all the files of this type, but when opening it in minecraft everything loads correctly.
![Captura](https://user-images.githubusercontent.com/112661134/189462405-dbff2704-4963-4ddf-b230-000d426fcddd.PNG)
[modelmonkey.zip](https://github.com/tom5454/CustomPlayerModels/files/9539321/modelmonkey.zip)

**Comment by tom5454** [comment] 2022-09-10 19:08
Open your model in-game, save it, so it is updated, then try Blockbench, some older models don't load in Blockbench.

**Comment by tom5454** [comment] 2022-09-22 19:12
Duplicate of #186

**Closed by tom5454** 2022-09-22 19:12 UTC
