### ISSUE TITLE
Animation update?

### ISSUE THREAD

**Issue by WillowWhyTfIsThisTaken** [tom5454/CustomPlayerModels#363] opened 2023-01-24 14:51 UTC
here are some points that would make the animation tab better in my opinion 
1. instead of frames keyframes, just like in blender or blockbench and changing the animation menu to a timeline with seconds 
2. an option for changing the scale of cubes while animating it

**Comment by hackercat27** [comment] 2023-01-24 15:45
if i'm not mistaken, the latter is already possible

**Comment by tom5454** [comment] 2023-02-14 18:08
The first is planned, the second you can already do that use the `Render Scale` option while animating.
Duplicate of #192

**Closed by tom5454** 2023-02-14 18:08 UTC
