### ISSUE TITLE
Blockbench wont let me export cpm models

### ISSUE THREAD

**Issue by GoldyFredy9** [tom5454/CustomPlayerModels#432] opened 2023-06-09 23:07 UTC
![image](https://github.com/tom5454/CustomPlayerModels/assets/109116387/f992e028-63df-44d9-9399-d0ce06a0b67e)

Every time i try to export the models from blockbench, i get thrown the same error.

This is the copied error:

Error while exporting:
TypeError: Cannot set properties of null (setting 'e')
    at com.tom.cpm.blockbench.convert.BlockbenchExport.convertUV(BlockbenchExport.java:1073) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1629:738)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.convert(BlockbenchExport.java:998) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1626:282)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport$lambda$lambda(BlockbenchExport.java:280) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1644:177)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport$lambda(BlockbenchExport.java:273) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1789:42)
    at com.tom.ugwt.client.JsArrayE.forEach(JsArrayE.java:20) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:6046:70)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:17:47)
    at Array.forEach (<anonymous>)
    at com.tom.ugwt.client.JsArrayE.forEach(JsArrayE.java:20) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1642:816)
    at com.tom.cpm.blockbench.convert.BlockbenchExport.doExport(BlockbenchExport.java:225) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1778:42)
    at com.tom.ugwt.client.JsArrayE.forEach(JsArrayE.java:20) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:6046:70)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:17:47)
    at Array.forEach (<anonymous>)
    at com.tom.ugwt.client.JsArrayE.forEach(JsArrayE.java:20) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1630:1011)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda$lambda(ProjectConvert.java:63) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1874:42)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1900:40)
    at com.tom.cpm.web.client.render.RenderSystem.withContext(RenderSystem.java:1239) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:5908:67)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport$lambda(ProjectConvert.java:60) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1873:23)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:59) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1899:55)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:17:47)
    at new Promise (<anonymous>)
    at com.tom.cpm.blockbench.convert.ProjectConvert.prepExport(ProjectConvert.java:59) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1898:47)
    at com.tom.cpm.blockbench.util.PopupDialogs.runTaskWithWarning(PopupDialogs.java:144) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:2028:32)
    at com.tom.cpm.blockbench.convert.ProjectConvert.exportWithWarnings(ProjectConvert.java:55) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1866:217)
    at com.tom.cpm.blockbench.format.CPMCodec.init(CPMCodec.java:48) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1932:52)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:17:47)
    at com.tom.cpm.blockbench.BBActions.load$lambda(BBActions.java:81) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:1550:63)
    at com.google.gwt.dev.jjs.intrinsic.com.google.gwt.lang.Runtime(Runtime.java:165) (https://tom5454.com/cpm/cpm_plugin/new/cpm_plugin.js?_=1686348132220:17:47)
    at Action.trigger (file:///C:/Users/Administrator/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/actions.js:314:10)
    at HTMLLIElement.<anonymous> (file:///C:/Users/Administrator/AppData/Local/Programs/Blockbench/resources/app.asar/js/interface/menu.js:308:9)
    at HTMLLIElement.dispatch (file:///C:/Users/Administrator/AppData/Local/Programs/Blockbench/resources/app.asar/lib/jquery.js:2:43064)
    at v.handle (file:///C:/Users/Administrator/AppData/Local/Programs/Blockbench/resources/app.asar/lib/jquery.js:2:41048)

**Comment by tom5454** [comment] 2023-06-09 23:25
Duplicate of #431

**Closed by tom5454** 2023-06-09 23:25 UTC
