### ISSUE TITLE
Client-side Multiplayer Crash (Pose Stack Not Empty)

### ISSUE THREAD

**Issue by KingShibaInu** [tom5454/CustomPlayerModels#379] opened 2023-03-01 03:53 UTC
Conflict with latest version of forge Customizaable Player Models and forge Supplementaries when attempting to run a disc in a jukebox when another player is within the jukebox radius: outcome; both clients crash, server unaffected.

**Comment by tom5454** [comment] 2023-03-02 21:23
Duplicate of #337

**Closed by tom5454** 2023-03-02 21:23 UTC
