### ISSUE TITLE
Mod not showing up on menu screen

### ISSUE THREAD

**Issue by LimonFotters** [tom5454/CustomPlayerModels#97] opened 2021-06-25 05:30 UTC
Usually when you install this mod and run fabric, it shows a little tab to bring you to the skin maker. But there's no tab when I load it up. I'm using the most recent version (CustomPlayerModelsFabric-1.17 v0.0.14a) along with the most recent fabric api (fabric-api-0.35.2+1.17)

**Comment by tom5454** [comment] 2021-06-25 12:29
Duplicate of #94

**Closed by tom5454** 2021-06-25 12:29 UTC
