### ISSUE TITLE
Cannot Export model (Cannot read properties of "a")

### ISSUE THREAD

**Issue by PepsRoni** [tom5454/CustomPlayerModels#367] opened 2023-01-31 21:12 UTC
File > Export to a CPM Project has stopped working for me and consistently displays this error prompt.
![Blockbench_iEZmJW5MDf](https://user-images.githubusercontent.com/124095932/215883786-fa1390ff-f395-44c6-b6e9-c31f984f25a6.png)

**Comment by tom5454** [comment] 2023-02-01 00:33
Please send a screenshot of the DevTools console (Ctrl+Shift+I)

**Comment by AusomeFace** [comment] 2023-02-01 03:43
Not original author, but I have the same issue.
![Screenshot 2023-01-31 224235](https://user-images.githubusercontent.com/73805001/215939981-007b1b6b-93af-4271-af3e-781163636bce.png)

**Comment by tom5454** [comment] 2023-02-01 13:01
Duplicate of #365

**Closed by tom5454** 2023-02-01 13:01 UTC
Labels: Blockbench
