### ISSUE TITLE
[bug / suggestion] The parts responsible for the second layer of the skin (and the parts attached to them) should be enabled and disabled based on the vanilla skin settings.

### ISSUE THREAD

**Issue by DearFox** [tom5454/CustomPlayerModels#215] opened 2022-04-30 11:16 UTC
These are the settings in question:
![image](https://user-images.githubusercontent.com/59219907/166103264-b5ea0a3d-a5ce-417f-be80-b7ab72399605.png)
their change is not reflected in any way on the character model, even if he had the second skin layer turned on.

**Comment by tom5454** [comment] 2022-05-06 19:05
The skin layers are used to send the custom poses/gestures. A combination of these toggles set the current pose/gesture. A toggleable gesture will be added in the future to the gestures menu.

**Comment by tom5454** [comment] 2022-05-06 19:05
Duplicate of #149

**Closed by tom5454** 2022-05-06 19:05 UTC
